homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 420
  unit_system: metric
  time_zone: Europe/Vienna
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    #- legacy_api_password
  packages: !include_dir_named packages

#ios:

frontend:

alexa: 
default_config:

custom_updater:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.11:3218

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_key

# http Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: dLha31AG
  trusted_networks:
    - 192.168.1.0/24
    - 127.0.0.1
    - ::1

#bmw_connected_drive:
#  name:
#    username: !secret bmw_connected_drive_username
#    password: !secret bmw_connected_drive_password
#    region: rest_of_world

sabnzbd:
  api_key: a7917fcdd30393745b8bdcd31cd067aa
  host: izeman.net
  name: sab
  port: 9090
  ssl: true
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

tado:
  username: !secret tado_username
  password: !secret tado_password

zoneminder:
  host: 192.168.1.100:8088
  username: !secret zoneminder_username
  password: !secret zoneminder_password
  ssl: true
  verify_ssl: false

camera:
  - platform: zoneminder

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

device_tracker:
  - platform: unifi
    host: 192.168.1.100
    username: !secret unifi_username
    password: !secret unifi_password
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
    verify_ssl: false
    ssid_filter:
      - 'izeman'

# Text to speech
tts:
  - platform: google

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
input_number: !include input_number.yaml
cover: !include covers.yaml
# alert: !include alerts.yaml
