- platform: mqtt
  name: "Poolpumpe"
  state_topic: "stat/poolpumpe/POWER1"
  command_topic: "cmnd/poolpumpe/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Waermepumpe"
  state_topic: "stat/waermepumpe/POWER1"
  command_topic: "cmnd/waermepumpe/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Poollicht"
  state_topic: "stat/poollicht/POWER"
  command_topic: "cmnd/poollicht/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "WorxCharger"
  state_topic: "stat/worxcharger/POWER"
  command_topic: "cmnd/worxcharger/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Schachtpumpe"
  state_topic: "stat/schachtpumpe/POWER"
  command_topic: "cmnd/schachtpumpe/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
